### ISSUE TITLE
Fix tabs,spaces,indentation

### ISSUE THREAD

**Issue by qx-775** [andreasgrafen/cascade#1]
Hi, just a small comment. The userChrome.css is badly formatted. 
There are lots of white spaces in between lines, and maybe the comments should have 1 white space each letter for readability? :)

Maybe format it with a tool such as prettier? Although I can't find CSS support for prettier at the moment, maybe another tool?
Anyways, thanks for your release. Tested it, looks pretty simple and solid
For example:

```css
/* Config */
:root {
    --bar-bg: #303035;
    --tab-active-bg: #404045;
}

/* General */
window,
#main-window,
#toolbar-menubar,
#TabsToolbar,
#PersonalToolbar,
#navigator-toolbox,
#sidebar-box,
#nav-bar {
    background-color: var(--bar-bg) !important;
    -moz-appearance: none !important;
    background-image: none !important;
    border: none !important;
    box-shadow: none !important;
}

.titlebar-buttonbox {
    display: none;
}

#tabbrowser-tabs[haspinnedtabs]:not([positionpinnedtabs])>#tabbrowser-arrowscrollbox>.tabbrowser-tab[first-visible-unpinned-tab] {
    margin-inline-start: 0 !important;
}

#TabsToolbar {
    margin-top: -1px !important;
    margin-bottom: 1px !important;
    margin-left: 25vw !important;
}

```
