### ISSUE TITLE
Option to hide url bar if unfocused

### ISSUE THREAD

**Issue by jacksongoode** [andreasgrafen/cascade#20]
It would be a great option if there was a way to hide the url bar until a user focuses (Ctrl+L) so tabs get maximum space.

**Comment by andreasgrafen** [comment]
I have been tinkering around with this idea for a bit. I haven't been able to come up with a solution to achieve exactly what you have described, as I can't figure out a way to target the tabs bar as a sibling while the url bar is active.

That said; I was able to come up with this alternative which will just completely overlay the tab bar with the url bar when it's active. There also is a really small hoverable area at the left hand side next to the tabs, but the prefered way would be to focus the url bar via keyboard.

```css
/* transition to oneline */
@media (min-width: 1000px) { 

    #nav-bar { background: var(--uc-theme-colour) !important; }
    
    #nav-bar:not([customizing]){
        margin: calc((var(--urlbar-min-height) * -1) - 8px) 100vw 0 0 !important;
        z-index: 2 !important;
    }
    
    #navigator-toolbox:focus-within > .browser-toolbar,
    #nav-bar:hover { margin: calc((var(--urlbar-min-height) * -1) - 8px) 0 0 0 !important; }


} /* end media query */
```
