### ISSUE TITLE
Is there possible to restore the menu button and make it on the far right

### ISSUE THREAD

**Issue by MrAru** [andreasgrafen/cascade#27]
Hi there. I found this great firefox theme and it's visually amazing. But I really need the menu button that come with the original Firefox theme. I commented out a few related lines in the theme file https://github.com/andreasgrafen/cascade/blob/98d50efef103b06fd61a3cc80fe9fabfb921c391/userChrome.css#L116-L128, but that didn't work as I expected.

![Screenshot_20220210_101156](https://user-images.githubusercontent.com/26517155/153325144-f430ea2e-fe57-463a-81dd-947cb42fd03e.png)

I would like to ask if it is possible to restore the display of the menu button and have it on the far right side of the title bar? Thanks.

**Comment by andreasgrafen** [comment]
Thanks a bunch and I'm happy you're liking Cascade! c:

The menu button is part of the URL bar which makes it a little tough to move it all the way to the right side. The only way I can think of from the top of my head is a little bit hacky.

```css
#PanelUI-button {
    
    position: fixed;
    top: 4px; right: 0;
    
    display: block;

}
```

While this works it might clash with other elements that are positioned on the right side of the top bar. You can avoid most issues by setting a padding for the tab container like this.

```css
#TabsToolbar { padding-right: 40px; }
```


![Changes in Action](https://user-images.githubusercontent.com/35840154/153387252-488e6458-891d-428e-98f5-1741925cbf25.png)
