### ISSUE TITLE
Color scheme change on the basis of firefox theme.

### ISSUE THREAD

**Issue by Rajbir98** [andreasgrafen/cascade#28]
like when the firefox theme is set to light the cascade theme would be light and when the firefox theme would be dark the cascade theme would be dark

**Comment by shahmilav** [comment]
Hey @Rajbir98 there is a way to do this.

In your userChrome.css, comment out the following lines.

```css
 :root {
    
    /* main window colour – toolbar & window background */
    --window-colour:    #1E2021;

    /* accent colour – active tab, button hover, ... */
    --secondary-colour: #191B1C;

    /* text and highlight colour */
    --inverted-colour:  #FAFAFC;

}
```

This will make the theme take on the colors of your current theme. Any theme works (even [this](https://addons.mozilla.org/en-US/firefox/addon/dark-knight-joker-theme/)), so you can browse [addons.mozilla.org](addons.mozilla.org) for something you like.

For more info, consult the [README](https://github.com/andreasgrafen/cascade#colours).
