### ISSUE TITLE
Is it possible to set text and icons color from within userChrome.css ?

### ISSUE THREAD

**Issue by HeiWiper** [andreasgrafen/cascade#4]
Currently, choosing white colors for `--window-colour` and `--secondary-colour` makes the text and icons invisible when the Firefox theme is dark.
Normally this isn't an issue since white theme users would probably apply the `userChrome.css` on a white Firefox theme but in my case I want to have a script to change between light and dark theme based on day time and your CSS file makes it really easy to just set the two colors, I would love if I also had the possibility to set the icons and text color.

**Comment by andreasgrafen** [comment]
I've noticed this as well, but as you said: This can easily be avoided by setting the browsers theme itself. There sadly doesn't seem to be a super simple way of setting all these colours from what I can tell; but maybe I'm just super blind. For some things like the tab text colour I straight up could not find a place where the colour is actually defined..

After a little bit of tinkering I think I have found a way to _hack_ this into the CSS.
The following variables exist by default and can be changed at will:
```CSS
/* default URL bar colour */
--toolbar-field-color: red !important;
     
/* active URL bar colour */
--toolbar-field-focus-color: blue !important;
     
/* suggestion highlight colour */
--autocomplete-popup-highlight-color: green !important;
```

There also are `--lwt-tab-text` which only seems to apply to the currently selected tab, and `--toolbar-color` which doesn't get applied from what I can tell. But If you would for example do something like the following you can use that variable to set the colours of icons and tabs.

```CSS
/* tab text and icon colour */
:root { --lwt-tab-text: pink !important; }

#main-window *,
#toolbar-menubar *,
#TabsToolbar *,
#PersonalToolbar *,
#navigator-toolbox *,
#sidebar-box *,
#nav-bar * { fill: var(--lwt-tab-text) !important; }

.tab-content { color: var(--lwt-tab-text) !important; }
```

---

With this in mind I would propose the next code-block as a solution.
It's a little messy with overwriting all the variables, but it seems to get the job done without messing up other UI elements; tho I'm sure this can be improved. Reading through the browser CSS styles is quite frustrating. I might take a look at other themes and how they handle this later in order to refactor my solution.

```CSS

 :root {
    
    --uc-text-colour: #FAFAFC; 
    
    --toolbar-field-color:		  var(--uc-text-colour) !important;
    --toolbar-field-focus-color:	  var(--uc-text-colour) !important;
    --autocomplete-popup-highlight-color: var(--uc-text-colour) !important;
    --lwt-tab-text:			  var(--uc-text-colour) !important;

}

#main-window *,
#toolbar-menubar *,
#TabsToolbar *,
#PersonalToolbar *,
#navigator-toolbox *,
#sidebar-box *,
#nav-bar * { fill: var(--lwt-tab-text) !important; }

.tab-content { color: var(--lwt-tab-text) !important; }

```
