### ISSUE TITLE
Multiple bugs with new update

### ISSUE THREAD

**Issue by Zabooby** [andreasgrafen/cascade#47]
Describe the bug
I made a fresh profile to test the new updates, installed it as instructed and am coming across several issues. The only setting I changed was --uc-urlbar-min-width: 0vw. 

Currently icons are in the wrong place and overlap, the tab bar isn't visible, sometimes the oneline breaks and the tab bar shows separately. 

My guess is that the default settings are messing things up?

The video below will showcase the bugs I'm experiencing.

Expected behaviour
Taken from my current setup, when not focused the url bar shrinks so the top bar can be entirely filled with tabs.
![image](https://user-images.githubusercontent.com/78969986/195978097-6669f7d3-8cec-4577-b1ff-56452a23b75f.png)

Video

https://user-images.githubusercontent.com/78969986/195978684-a238c1b0-71ce-4e3c-90cd-d979ac2fc0eb.mp4

**Comment by andreasgrafen** [comment]
That indeed doesn't look good. I've tried a couple of things but can't reproduce this behaviour at all which makes it harder to approach. If you rightclick the toolbar and go into the customisation settins, are there any additional items or spacers placed in there that could cause this to break?

[bar.webm](https://user-images.githubusercontent.com/35840154/195991487-72f1befd-c6b2-482a-b42b-b7e4bb5f0ba7.webm)

**Comment by Zabooby** [comment]
Yup I always do that when installing Firefox, got rid of the empty space things and the rest of it.

In my current setup I also have these enabled in about:config could that be making a difference?

layers.acceleration.force-enabled
gfx.webrender.all
svg.context-properties.content.enabled

**Comment by andreasgrafen** [comment]
Hmm.. so it's not the spacers or anything; there goes my best guess. Does it also switch to the tab overflow mode when you just have one or two tabs open? o:

If you want the Toolbar to be below the Nav- and Tab Bar you can change that in the [settings file](https://github.com/andreasgrafen/cascade/blob/main/chrome/includes/cascade-config.css#L41) by setting the variable to `4`. Since Cascade is using `Flexbox` under the hood this really is just the `flex-order` property being set.
```css
  /*  Position of the Personal Toolbar
   *  possible values:
   *  0 – toolbar on top
   *  4 – toolbar on bottom
   */ --uc-toolbar-position: 4;
```

The Tab width can also be changed in the [config file](https://github.com/andreasgrafen/cascade/blob/main/chrome/includes/cascade-config.css#L110) tho this really only affects the widths of the individual tabs and should not have any influence on the Tab Bar itself.
```css
  /*  Allow tabs to have dynamic widths based on
   *  the Tab Bars maximum width
   */ --uc-active-tab-width:   clamp(100px, 30vw, 300px);
      --uc-inactive-tab-width: clamp(100px, 20vw, 200px);
```

The extra settings you've mentions also don't make a difference as I have them enabled too, they're just not necessary for Cascade which is why I removed them from the install instructions.

**Comment by Zabooby** [comment]
Ok after reinstalling it again, making sure the toolbar was completely cleaned up and moving some icons around the overlapping is fixed and the oneline doesn't break like in the video. With min with of the url bar as 0 it is working as expected. 

The only issues that are still happening are the tabs not showing and the bookmarks bar being at the top. 

I'll check the config file when I'm at my pc.

**Comment by Zabooby** [comment]
Toolbar is now in the right place.

It goes into tab overflow mode when I have one tab open.

**Comment by andreasgrafen** [comment]
That's so weird … I've tried a lot to reproduce this. Fullscreen, non-fullscreen, adding spacer, moving around icons.. There is nothing that breaks it like this on my end. The only thing I can think of now is that it might be system specific for some reason?

<img width="146" alt="Screen Shot 2022-10-15 at 18 20 58" src="https://user-images.githubusercontent.com/35840154/195997108-b91f5d34-2bab-45c4-879e-6596d524ea01.png">
In your first screenshot you have window control buttons, but they don't appear in the video. The screenshot also shows the tab like it should be which is even more confusing.. o:
I'm sorry, but right now I have no idea how to tackle this issue. :/

**Comment by Zabooby** [comment]
Oh, that was taken from my current setup which is using the old cascade setup. 

Are you on windows too?

**Comment by andreasgrafen** [comment]
ooh! Okay, so there is a difference.
And no, I've only tested this on Mac and Linux. I've banished Windows from my machines ages ago.. Maybe I should set up a VM for testing purposes. I'll do that right away and hopefully that will help in resolving this.

**Comment by Zabooby** [comment]
Fair enough, I've browsed r/unixporn and have been tempted to switch in the past.

Just spitballing, maybe its a scaling issue, I'm running 1920x1080 at 100% (windows usually recommends 125% at my res).

**Comment by andreasgrafen** [comment]
I don't think that screen resultion pays a role in this. I've put a blindly suggested solution in [Issue 49](https://github.com/andreasgrafen/cascade/issues/49#issuecomment-1279852160). Maybe setting that value works with fixing the Tabs issue.

**Comment by andreasgrafen** [comment]
It seems like `flexbox` (within the Firefox UI) is inheritly broken on Windows. In order to fix the One-Line layout on windows please substitute the [responsive include](chrome/includes/cascade-responsive.css) with the [version for windows](chrome/includes/cascade-responsive-windows-fix.css). This will ensure that the layout doesn't break **but** since it can't use `flexbox` the UI reordering does **not** work.<br>

**Comment by Zabooby** [comment]
As minimising the url bar won't work, is there any point for me to even change from my current setup, everything else will be the same?

Is it worth making a post on r/firefoxcss about `flexbox` to see if anyone can help or is there nothing that can be done by css enthusiast?

**Comment by andreasgrafen** [comment]
Ah, right.. the hidden URL Bar. You *could* try the following CSS snippet, this is close to what my first tests for that feature were, but it in 1 out of 50 cases bugs out for some reason.
```css
@media (min-width: 1000px) {

  #nav-bar { margin: calc((var(--urlbar-min-height) * -1) - 10px) calc(100vw - var(--uc-urlbar-min-width)) 0 0 !important; }
  #titlebar { margin-inline-start: var(--uc-urlbar-min-width) !important; }

  #navigator-toolbox:focus-within #nav-bar { margin-inline-end: 100vw !important; }
  #navigator-toolbox:focus-within #titlebar { width: 100vw !important; }

}
```

I've been in touch with a couple people about this already, but no luck so far. Maybe reaching out to a broader set of people would help. I'll give it a shot. c:

**Comment by Zabooby** [comment]
I replaced [this](https://github.com/andreasgrafen/cascade/blob/main/chrome/includes/cascade-responsive-windows-fix.css) but all it does is black out the url bar. :(

![image](https://user-images.githubusercontent.com/78969986/196052905-029c1ae2-31f6-43aa-8635-40f51e0ea1c9.png)

**Comment by andreasgrafen** [comment]
Okay, so … turns out I shouldn't answer with code snippets I wrote without testing shortly after waking up … Jeebus I completely butchered that.
I gave it a quick shot and this one should work
```css
@media (min-width: 1000px) {

  #nav-bar { margin: calc((var(--urlbar-min-height) * -1) - 10px) 100vw 0 0 !important; }
  #titlebar { margin-inline-start: 0 !important; }

  #navigator-toolbox:focus-within #nav-bar { margin: calc((var(--urlbar-min-height) * -1) - 10px) 0 0 0 !important; }
  #navigator-toolbox:focus-within #titlebar { margin-inline-start: 100vw !important; }

}
```

Sorry for that. o:

**Comment by Zabooby** [comment]
Np, this works but the url bar doesn't show on hover, only when I use a hot key. Also it takes up the whole bar when in focus but I should be able to change one of the numbers to fix that right? 

How close can you get to the functionality of using `flexbox` with this method?

**Comment by andreasgrafen** [comment]
To make it work on hover too this should be the code to go. Also updated to respect the values set in the cascade config file. c:
```css
@media (min-width: 1000px) {

  #nav-bar { margin: calc((var(--urlbar-min-height) * -1) - 12px) calc(100vw - var(--uc-urlbar-min-width)) 0 0 !important; }
  #titlebar { margin-inline-start: var(--uc-urlbar-min-width) !important; }

  #navigator-toolbox:focus-within #nav-bar,
  #navigator-toolbox:hover #nav-bar { margin: calc((var(--urlbar-min-height) * -1) - 12px) calc(100vw - var(--uc-urlbar-max-width)) 0 0 !important; }
  
  #navigator-toolbox:focus-within #titlebar,
  #navigator-toolbox:hover #titlebar { margin-inline-start: var(--uc-urlbar-max-width) !important; }

}
```

The functionality is like 75- to 80-ish percent of what flexbox can do? Flex just makes it a lot easier and less error prone I feel like.
