### ISSUE TITLE
Layout and color bugs on Windows

### ISSUE THREAD

**Issue by TheNetAdmin** [andreasgrafen/cascade#49]
**Describe the bug**

I'm using Firefox 105.0.3 on Windows 10, and cascade has layout and color bugs as shown in the screenshot:

1. As #47 mentioned, the tabs are squeezed and overlapped, as shown on the right side of the URL bar
2. The cascade color does not work, everything is just plain color, not as show in the README
   > The previous cascade's color also doesn't work on Windows Firefox
3. ~The responsive oneliner style doesn't work, no matter how I change the Firfox window width, it's always oneliner with the above bugs~ Update: not an issue on Windows, I didn't narrow the window enough to trigger the two line style.

This screenshot is taken after a clean install of Firefox, without any add-on or config.

**Expected behavior**

The tabs should be displayed as show in the README, not squeezed into a tiny region, and colors should work.

**Additional info**

I found commenting the following line will make the URL bar under the tab bar and that works fine. But I want the oneliner style

https://github.com/andreasgrafen/cascade/blob/504215d1e245cbd135e866e0cb12e0c8e06a0805/chrome/includes/cascade-responsive.css#L4

**Screenshots** (optional)

![image](https://user-images.githubusercontent.com/18525442/196010086-f74536e3-97f5-49cc-8d58-142d34d7e829.png)

**Comment by TheNetAdmin** [comment]
I might be able to help with debugging on Windows, but IDK where to start. Maybe we can discuss something to try and I can post the results here.

**Comment by andreasgrafen** [comment]
Uugh, so **it is** a Windows issue. Part of me just wants to say that I don't support Windows – done.. **But yeah, that sadly is not an option**, I guess. :D

I'd assume that points **1** and **3** are tightly connected.
This is a complete shot in the blue, but could you try to add `#TabsToolbar { width: 100% !important; }` into the [responsive layout file](https://github.com/andreasgrafen/cascade/blob/main/chrome/includes/cascade-responsive.css)? That *should* scale the inner Tabbar container to the full width available and I wonder if that at least helps with the One-Line layout on windows.
cc: #47 

Regarding the colour issue – first of all; good to know that this issue also happens with v2. I'll boldly assume that #48 is Windows related as well. I'd hope that the suggested solution there works, but I don't have the highest of hopes.

**Comment by TheNetAdmin** [comment]
I've added the line but it still doesn't work:

![image](https://user-images.githubusercontent.com/18525442/196011393-196c4182-ac69-432a-8082-8e32f34f3f7a.png)


```css
@media (min-width: 1000px) {


  #navigator-toolbox { display: flex; flex-wrap: wrap; }
  #TabsToolbar { width: 100% !important; }

  #nav-bar {

    order: var(--uc-urlbar-position);
    width: var(--uc-urlbar-min-width);

  }


  #titlebar {

    order: 2;
    width: calc(100vw - var(--uc-urlbar-min-width) - 1px);

  }


  #PersonalToolbar {

    order: var(--uc-toolbar-position);
    width: 100%;

  }


  #navigator-toolbox:focus-within #nav-bar { width: var(--uc-urlbar-max-width); }
  #navigator-toolbox:focus-within #titlebar { width: calc(100vw - var(--uc-urlbar-max-width) - 1px); }


}

```

**Comment by TheNetAdmin** [comment]
And problem 3 seems to be not an issue, I just did not narrow the window enough... I have a wide screen and didn't realize what 1000px should look like on this screen.

**Comment by andreasgrafen** [comment]
Meh… It was worth a shot. But, wait.. that screenshot regarding your third point still shows the overflow indicators for the tab bar. That kinda makes it seem like this is not an issue with the One-Line layout, but happens as a general problem.

I really wonder what causes this.. could you, just for the sake of it, try to set the same line as mentioned above in the [regular layout include](https://github.com/andreasgrafen/cascade/blob/main/chrome/includes/cascade-layout.css)? It didn't change anything on the One-Line layout, so I'd assume that this wouldn't result in this being fixed, but better be safe than sorry. c:

**Comment by TheNetAdmin** [comment]
I've tried but it still doesn't work, here is the code:

```css

#TabsToolbar { width: 100% !important; }

:root {

  --toolbarbutton-border-radius: var(--uc-border-radius) !important;
  --tab-border-radius: var(--uc-border-radius) !important;
  --arrowpanel-border-radius: var(--uc-border-radius) !important;

}




#main-window,
#toolbar-menubar,
#TabsToolbar,
#navigator-toolbox,
#sidebar-box,
#nav-bar { box-shadow: none !important; }


#main-window,
#toolbar-menubar,
#TabsToolbar,
#PersonalToolbar,
#navigator-toolbox,
#sidebar-box,
#nav-bar {

  -moz-appearance: none !important;
  border: none !important;

}


/* remove "padding" left and right from tabs */
.titlebar-spacer { display: none !important; }





#PersonalToolbar {

  padding: 6px !important;
  box-shadow: inset 0 0 50vh rgba(0, 0, 0, var(--uc-darken-toolbar)) !important;;

}





#statuspanel #statuspanel-label {

  border: none !important;
  border-radius: var(--uc-border-radius) !important;

}

```

And screenshots

![image](https://user-images.githubusercontent.com/18525442/196011898-c470228a-cf86-4d6c-a71f-c9b98b9b2d57.png)

![image](https://user-images.githubusercontent.com/18525442/196011906-205756d2-54b0-4ec5-a72d-1d563efba1d5.png)

**Comment by andreasgrafen** [comment]
Okay, so I'm on a borrowed windows machine now. The issue is that for some reason the Titlebar just has an effective width of `0` no matter how much space there is and no matter what value is set via CSS. It just refuses to take up space, which is .. weird.

**Comment by andreasgrafen** [comment]
Update.. the overflow indicators are only showing up on the Tabbar if the Browser Window has been in Oneline Mode before. If the window opens in stacked everything looks and works fine.
So the Issue is def. somewhere within the responsive layout..

![debugging time](https://i.imgur.com/aAD6hRW.gif)

**Comment by andreasgrafen** [comment]
Okay.. turns out that Windows has inherant issues with `flexbox` itself when it comes to laying out UI elements.. This kinda makes this unfixable tho, as the alternatives (i.e. `-moz-box` don't allow for the same amount of customisation.

**But** using the same method as used in v2 we can at least achieve a simple version of the One-Line layout (tho without any of the reorderding capabilities) on windows.
To do this simply replace the responsive include with:
```css
@media (min-width: 1000px) {

  #nav-bar { margin: calc((var(--urlbar-min-height) * -1) - 10px) calc(100vw - var(--uc-urlbar-min-width)) 0 0 !important; }
  #titlebar { margin-inline-start: var(--uc-urlbar-min-width) !important; }

}
```
