### ISSUE TITLE
How to move the sidebar of tcr to right

### ISSUE THREAD

**Issue by ayamir** [andreasgrafen/cascade#79]
**Describe the solution you'd like**
move the sidebar of tcr to right.
**Is your feature request related to a problem? Please describe.**
No

**Comment by andreasgrafen** [comment]
To achieve this you need to open the sidebar, either with different content or with the TCR integration disabled, and move it to the right via the Sidebar-Header-Menu.
<img width="226" alt="Screenshot 2023-04-09 at 17 45 19" src="https://user-images.githubusercontent.com/35840154/230782631-784311d9-88c9-4efa-a933-dd66d2ca1d74.png">

Tho doing this will probably render a portion of the CSS more or less useless and it would have to be rewritten to accomodate for the flipped direction of things.

**Comment by ayamir** [comment]
Yes, I have move it to right via tcr's "Move Sidebar to Right".
![image](https://user-images.githubusercontent.com/61657399/230783644-04eb3c7b-f741-4967-bcb8-f2efbf0cb342.png)

But it shows in left back after apply cascade and tcr.

**Comment by andreasgrafen** [comment]
Hmm; yeah.. that's what I meant with that some of the CSS may have to be rewritten.
By the look of it you'd need to tell it explicitally that the [right position](https://github.com/andreasgrafen/cascade/blob/main/integrations/tabcenter-reborn/cascade-tcr.css#L14) should be `0`. Furthermore setting the margin to `right` on line [32](https://github.com/andreasgrafen/cascade/blob/main/integrations/tabcenter-reborn/cascade-tcr.css#L32) and [33](https://github.com/andreasgrafen/cascade/blob/main/integrations/tabcenter-reborn/cascade-tcr.css#L33) may also be necessary for the browser content window to be positioned correctly.

**Comment by ayamir** [comment]
Thanks for your help! Here is the code for others with the same requirement like me.
```css
#TabsToolbar { display: none !important; }
#nav-bar { width: 100vw !important; }



#browser { position: relative; }
#sidebar-box[sidebarcommand*="tabcenter"] #sidebar-header { display: none; }

#sidebar-box[sidebarcommand*="tabcenter"]:not([hidden]) {

  display: block;

  position: absolute;
  top: 0; bottom: 0; right: 0;
  z-index: 1;

  min-width: 50px !important; max-width: 50px !important;

  border-right: none;

  transition: all 0.2s ease;

  overflow: hidden;

}

[sidebarcommand*="tabcenter"] #sidebar,
#sidebar-box[sidebarcommand*="tabcenter"]:hover { min-width: 10vw !important; width: 30vw !important; max-width: 250px !important; }

[sidebarcommand*="tabcenter"] #sidebar { height: 100%; max-height: 100%; }

#sidebar-box[sidebarcommand*="tabcenter"]:not([hidden]) ~ #appcontent { margin-right: 50px; }
#main-window[inFullscreen][inDOMFullscreen] #appcontent { margin-right: 0; }
/* Removes gap between active tab highlight and edge of bar */
#sidebar-box[sidebarcommand="tabcenter-reborn_ariasuni-sidebar-action"] #sidebar-header, #sidebar-box[sidebarcommand="tabcenter-reborn_ariasuni-sidebar-action"] ~ #sidebar-splitter {
    display: none;
}

```
